### ISSUE TITLE
ICS subscription issue - External Calendar module (1.1.11) with HumHub 1.6.x

### ISSUE THREAD

**Issue by tinkat69** [humhub-contrib/external-calendar#18] opened 2020-08-13 10:34 UTC
To reproduce:

* from calendar in HumHub, go to calendar export to generate .ics file/link
* input link to create a new subscription in an external calendar or iCal validator

Comments:
Not sure whether this is primarily an External Calendar Module issue or HumHub core but when using External Calendar with HumHub 1.6.x,, inputting the generated .ics export link to a client calendar or iCal validator, the clients are not able to access a generated .ics /VCALENDAR file, only html.

As the same Calendar (1.0.12 ) and External Calendar module (1.1.11) versions are currently working fine (re ics subscriptions) with another HumHub installation (1.5.x), presumably this is an issue in combination with 1.6.x  preventing clients from accessing a generated ics file?

(The above referred-to HumHub 1.5.x installation- completely different server environment - has now been updated to 1.6.2 and the generated ics. links for subscribing to the calendar are facing the same problem.)

Many thanks!

**Comment by buddh4** [comment] 2020-09-14 16:58
Yes, there was an access check change in 1.6. Should be a quick fix, thanks for the note!

**Comment by buddh4** [comment] 2020-09-14 17:03
Should be fixed in https://github.com/humhub-contrib/external-calendar/commit/9117693b4cd4b99ebb2db1d338ff1b9b551644c3#diff-6124887fb886d2cf54dbca3f98779ea1R23 can you confirm the issue is solved by the selected line?

**Comment by tinkat69** [comment] 2020-09-15 09:01
Yes, it's working again now. Well done and thanks!

FYI testing with a validator (icalendar.org), errors are shown for events with specific times i.e. not whole day:
e.g. 'Invalid TZID value or missing VTIMEZONE component (Europe/Berlin) near line # 24Reference: 3.2.19. Time Zone Identifier'.
The Termine/appointments are showing up fine in the actual client calendars though.

**Comment by buddh4** [comment] 2020-09-15 09:44
Hi thanks for testing, can you open another issue for this. Unfortunately timezones in ics are a bit tricky.

**Closed** 2020-09-15 09:46 UTC
Labels: bug
